import { NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { loans, loanReturns } from '@/lib/db/schema'
import { requireAdmin } from '@/lib/admin-auth'
import { desc, eq } from 'drizzle-orm'

export async function GET() { const session = await requireAdmin(); if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const rows = await db.select().from(loans).orderBy(desc(loans.loanDate)); const returns = await db.select().from(loanReturns); return NextResponse.json(rows.map((loan) => ({ ...loan, returned: returns.filter((item) => item.loanId === loan.id).reduce((sum, item) => sum + item.amount, 0), balance: loan.amount - returns.filter((item) => item.loanId === loan.id).reduce((sum, item) => sum + item.amount, 0) }))) }
export async function POST(request: Request) { const session = await requireAdmin(); if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const body = await request.json(); const amount = Number(String(body.amount ?? '').replace(/,/g, '')); if (!body.borrower || !Number.isFinite(amount) || amount <= 0 || !body.purpose) return NextResponse.json({ error: 'Borrower, amount and purpose are required.' }, { status: 400 }); const [row] = await db.insert(loans).values({ id: crypto.randomUUID(), borrower: String(body.borrower).trim(), amount: Math.round(amount), purpose: String(body.purpose).trim(), loanDate: body.loanDate ? new Date(body.loanDate) : new Date(), dueDate: body.dueDate ? new Date(body.dueDate) : null, notes: body.notes ? String(body.notes) : null, agreementText: body.agreementText ? String(body.agreementText) : null, agreementPhotoPath: body.agreementPhotoPath ? String(body.agreementPhotoPath) : null, status: 'active', createdBy: session.user.id }).returning(); return NextResponse.json(row, { status: 201 }) }
export async function PATCH(request: Request) { const session = await requireAdmin(); if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const body = await request.json(); const [row] = await db.update(loans).set({ borrower: String(body.borrower), amount: Math.round(Number(String(body.amount).replace(/,/g, ''))), purpose: String(body.purpose), loanDate: body.loanDate ? new Date(body.loanDate) : undefined, dueDate: body.dueDate ? new Date(body.dueDate) : null, notes: body.notes ? String(body.notes) : null, agreementText: body.agreementText ? String(body.agreementText) : null, agreementPhotoPath: body.agreementPhotoPath ? String(body.agreementPhotoPath) : null }).where(eq(loans.id, String(body.id))).returning(); return NextResponse.json(row) }
export async function DELETE(request: Request) { const session = await requireAdmin(); if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const { id } = await request.json(); await db.delete(loans).where(eq(loans.id, String(id))); return NextResponse.json({ ok: true }) }
export async function PUT(request: Request) { const session = await requireAdmin(); if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const body = await request.json(); const amount = Math.round(Number(String(body.amount).replace(/,/g, ''))); if (!body.loanId || !Number.isFinite(amount) || amount <= 0) return NextResponse.json({ error: 'Loan and valid return amount are required.' }, { status: 400 }); const [row] = await db.insert(loanReturns).values({ id: crypto.randomUUID(), loanId: String(body.loanId), amount, returnDate: body.returnDate ? new Date(body.returnDate) : new Date(), notes: body.notes ? String(body.notes) : null, createdBy: session.user.id }).returning(); return NextResponse.json(row, { status: 201 }) }
