import { NextResponse } from 'next/server'
import { eq } from 'drizzle-orm'
import { db } from '@/lib/db'
import { applications, announcements, content, contactMessages, expenses, gallery, members, programs, works } from '@/lib/db/schema'
import { requireAdmin } from '@/lib/admin-auth'

const tables = { members, content, expenses, applications, works, programs, gallery, announcements, contactMessages } as const
const valid = (kind: string) => Object.prototype.hasOwnProperty.call(tables, kind)
const table = (kind: string) => tables[kind as keyof typeof tables]

export async function GET(request: Request) { try { if (!await requireAdmin()) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const kind = new URL(request.url).searchParams.get('kind') ?? 'members'; const selected = table(kind); if (!selected || !valid(kind)) return NextResponse.json({ error: 'Invalid module' }, { status: 400 }); return NextResponse.json(await db.select().from(selected as never)) } catch { return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }) } }
export async function POST(request: Request) { try { const session = await requireAdmin(); if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const kind = new URL(request.url).searchParams.get('kind') ?? ''; const body = await request.json(); const id = crypto.randomUUID(); let result
  if (kind === 'members') result = await db.insert(members).values({ id, name: String(body.name), role: String(body.role ?? 'Member'), ward: body.ward ?? null, phone: body.phone ?? null, email: body.email ? String(body.email).trim().toLowerCase() : null, status: String(body.status ?? 'active') }).returning()
  else if (kind === 'content') result = await db.insert(content).values({ id, section: String(body.section), title: String(body.title), body: String(body.body), updatedBy: session.user.id }).returning()
  else if (kind === 'expenses') result = await db.insert(expenses).values({ id, title: String(body.title), amount: Number(String(body.amount ?? 0).replace(/,/g, '')), purpose: String(body.purpose), spentAt: body.spentAt ? new Date(String(body.spentAt)) : new Date(), receiptUrl: body.receiptUrl ?? null, createdBy: session.user.id }).returning()
  else if (kind === 'applications') result = await db.insert(applications).values({ id, name: String(body.name), phone: String(body.phone), email: body.email ? String(body.email).trim().toLowerCase() : null, message: body.message ?? null, status: String(body.status ?? 'pending') }).returning()
  else if (kind === 'works') result = await db.insert(works).values({ id, title: String(body.title), description: String(body.description ?? ''), location: body.location ?? null, responsible: body.responsible ?? null, status: String(body.status ?? 'pending'), budget: Number(body.budget ?? 0), actualExpense: Number(body.actualExpense ?? 0), createdBy: session.user.id }).returning()
  else if (kind === 'programs') result = await db.insert(programs).values({ id, name: String(body.name), description: String(body.description ?? ''), location: body.location ?? null, organizedBy: body.organizedBy ?? null, responsible: body.responsible ?? null, status: String(body.status ?? 'upcoming'), budget: Number(body.budget ?? 0), actualExpense: Number(body.actualExpense ?? 0), createdBy: session.user.id }).returning()
  else if (kind === 'gallery') result = await db.insert(gallery).values({ id, title: String(body.title), description: body.description ?? null, category: String(body.category ?? 'Other'), imageUrl: String(body.imageUrl), createdBy: session.user.id }).returning()
  else if (kind === 'announcements') result = await db.insert(announcements).values({ id, title: String(body.title), body: String(body.body), category: String(body.category ?? 'Update'), published: body.published !== false, createdBy: session.user.id }).returning()
  else return NextResponse.json({ error: 'Invalid module' }, { status: 400 }); return NextResponse.json(result?.[0], { status: 201 }) } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Create failed' }, { status: 400 }) } }
export async function PATCH(request: Request) { try { const session = await requireAdmin(); if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const kind = new URL(request.url).searchParams.get('kind') ?? ''; const body = await request.json(); const id = String(body.id); let result
  if (kind === 'members') result = await db.update(members).set({ name: String(body.name), role: String(body.role), ward: body.ward ?? null, phone: body.phone ?? null, email: body.email ? String(body.email).trim().toLowerCase() : null, status: String(body.status ?? 'active'), updatedAt: new Date() }).where(eq(members.id, id)).returning()
  else if (kind === 'content') result = await db.update(content).set({ section: String(body.section), title: String(body.title), body: String(body.body), updatedAt: new Date(), updatedBy: session.user.id }).where(eq(content.id, id)).returning()
  else if (kind === 'expenses') result = await db.update(expenses).set({ title: String(body.title), amount: Number(String(body.amount ?? 0).replace(/,/g, '')), purpose: String(body.purpose), spentAt: body.spentAt ? new Date(String(body.spentAt)) : undefined, receiptUrl: body.receiptUrl ?? null }).where(eq(expenses.id, id)).returning()
  else if (kind === 'applications') result = await db.update(applications).set({ name: String(body.name), phone: String(body.phone), email: body.email ? String(body.email).trim().toLowerCase() : null, message: body.message ?? null, status: String(body.status ?? 'pending') }).where(eq(applications.id, id)).returning()
  else if (kind === 'works') result = await db.update(works).set({ title: String(body.title), description: String(body.description ?? ''), location: body.location ?? null, responsible: body.responsible ?? null, status: String(body.status ?? 'pending'), budget: Number(body.budget ?? 0), actualExpense: Number(body.actualExpense ?? 0) }).where(eq(works.id, id)).returning()
  else if (kind === 'programs') result = await db.update(programs).set({ name: String(body.name), description: String(body.description ?? ''), location: body.location ?? null, organizedBy: body.organizedBy ?? null, responsible: body.responsible ?? null, status: String(body.status ?? 'upcoming'), budget: Number(body.budget ?? 0), actualExpense: Number(body.actualExpense ?? 0) }).where(eq(programs.id, id)).returning()
  else if (kind === 'gallery') result = await db.update(gallery).set({ title: String(body.title), description: body.description ?? null, category: String(body.category ?? 'Other'), imageUrl: String(body.imageUrl) }).where(eq(gallery.id, id)).returning()
  else if (kind === 'announcements') result = await db.update(announcements).set({ title: String(body.title), body: String(body.body), category: String(body.category ?? 'Update'), published: body.published !== false }).where(eq(announcements.id, id)).returning()
  else return NextResponse.json({ error: 'Invalid module' }, { status: 400 }); return NextResponse.json(result?.[0] ?? null) } catch { return NextResponse.json({ error: 'Update failed' }, { status: 400 }) } }
export async function DELETE(request: Request) { try { if (!await requireAdmin()) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const kind = new URL(request.url).searchParams.get('kind') ?? ''; const id = String((await request.json()).id); const selected = table(kind); if (!selected || !valid(kind)) return NextResponse.json({ error: 'Invalid module' }, { status: 400 }); await db.delete(selected as never).where(eq((selected as { id: typeof members.id }).id, id)); return NextResponse.json({ ok: true }) } catch { return NextResponse.json({ error: 'Delete failed' }, { status: 400 }) } }
